# - KPIs:
***
***

### - Carga de librerias y de datos en Variables

In [1]:
# Importa libreria
import pandas as pd

In [2]:
# Carga el archivo en una Variable
kpi = pd.read_excel('Data/eda_general.xlsx')

In [24]:
# Carga el archivo en una Variable
habitantes_por_comuna = pd.read_excel('Data/comunas_habitantes.xlsx')

***
***
# KPI_1

  1 _ Reducir en un 10% la tasa de homicidios en siniestros viales de los últimos seis meses, en CABA, en comparación con la tasa de      homicidios en siniestros viales del semestre anterior.

- Definimos a la tasa de homicidios en siniestros viales como el número de víctimas fatales en accidentes de tránsito por cada 100,000 habitantes en un área geográfica durante un período de tiempo específico. Su fórmula es: (Número de homicidios en siniestros viales / Población total) * 100,000

In [3]:
# Visuallizacion general del DataFrame
kpi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 715 entries, 0 to 714
Data columns (total 35 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Id                     715 non-null    object
 1   N°_Victimas            715 non-null    int64
 2   Fecha_Hechos           715 non-null    datetime64[ns]
 3   Año_Hechos             715 non-null    int64
 4   Mes_Hechos             715 non-null    int64
 5   Dia_Hechos             715 non-null    int64
 6   Hora_Completa_Hechos   714 non-null    datetime64[ns]
 7   Hora_Hechos            715 non-null    object
 8   Lugar_Del_Hecho        715 non-null    object
 9   Tipo_De_Calle          715 non-null    object
 10  Calle                  715 non-null    object
 11  Altura                 133 non-null    float64
 12  Cruce                  540 non-null    object
 13  Dirección Normalizada  707 non-null    object
 14  Comuna                 715 non-null    int64
 15  Barrios                715 non-null    object
 16  Poblacion              715 non-null    int64
 17  Geo_Localizacion       715 non-null    object
 18  Longitud               706 non-null    float64
 19  Latitud                706 non-null    float64
 20  Victima                715 non-null    object
 21  Sexo                   715 non-null    object
 22  Edad                   664 non-null    float64
 23  Rol_Victima            715 non-null    object
 24  Acusado                715 non-null    object
 25  Participantes          715 non-null    object
 26  Fecha_Fallecimiento    648 non-null    datetime64[ns]
 27  Año_Fallecimiento      648 non-null    float64
 28  Mes_Fallecimiento      648 non-null    float64
 29  Dia_Fallecimiento      648 non-null    float64
 30  Meses_Nombres_Hechos   715 non-null    object
 31  Dias_Nombres_Hechos    715 non-null    object
 32  COMUNAS                715 non-null    int64
 33  Area                   715 non-null    float64
 34  Densidad_Poblacion     715 non-null    float64
dtypes: datetime64[ns](3), float64(9), int64(7), object(16)
memory usage: 195.6+ KB

In [4]:
# Se observan las % primeras filas
kpi.head()

,Id,N°_Victimas,Fecha_Hechos,Año_Hechos,Mes_Hechos,Dia_Hechos,Hora_Completa_Hechos,Hora_Hechos,Lugar_Del_Hecho,Tipo_De_Calle,...,Participantes,Fecha_Fallecimiento,Año_Fallecimiento,Mes_Fallecimiento,Dia_Fallecimiento,Meses_Nombres_Hechos,Dias_Nombres_Hechos,COMUNAS,Area,Densidad_Poblacion
0,2016-0001,1,2016-01-01,2016,1,1,1900-01-01 04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,MOTO-AUTO,2016-01-01,2016.0,1.0,1.0,Enero,Viernes,8,2.221690e+07,0.010202
1,2016-0004,1,2016-01-10,2016,1,10,1900-01-01 00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,MOTO-SD,NaT,NaN,NaN,NaN,Enero,Domingo,8,2.221690e+07,0.010202
2,2016-0008,1,2016-01-24,2016,1,24,1900-01-01 18:30:00,18,AV 27 DE FEBRERO Y AV ESCALADA,AVENIDA,...,MOTO-OBJETO FIJO,2016-01-24,2016.0,1.0,24.0,Enero,Domingo,8,2.221690e+07,0.010202
3,2016-0017,1,2016-02-15,2016,2,15,1900-01-01 16:54:00,16,MARIANO ACOSTA Y ANA MARIA JANER,AVENIDA,...,PEATON-MOTO,2016-02-16,2016.0,2.0,16.0,Febrero,Lunes,8,2.221690e+07,0.010202
4,2016-0025,1,2016-02-28,2016,2,28,1900-01-01 04:50:00,4,AV GRAL PAZ Y AV 27 DE FEBRERO,GRAL PAZ,...,AUTO-AUTO,2016-02-28,2016.0,2.0,28.0,Febrero,Domingo,8,2.221690e+07,0.010202

### Generar una funcion para dividir el año y crear una columna 'Semestre'

In [5]:
# Definir una función para asignar el número del semestre
def asignar_semestre(mes):
    if 1 <= mes <= 6:
        return 1
    elif 7 <= mes <= 12:
        return 2
    else:
        return None

# Aplicar la función a la columna 'MM' para crear la columna 'semestre'
kpi['Semestre'] = kpi['Mes_Hechos'].apply(asignar_semestre)

# Mostrar el DataFrame resultante
kpi

,Id,N°_Victimas,Fecha_Hechos,Año_Hechos,Mes_Hechos,Dia_Hechos,Hora_Completa_Hechos,Hora_Hechos,Lugar_Del_Hecho,Tipo_De_Calle,...,Fecha_Fallecimiento,Año_Fallecimiento,Mes_Fallecimiento,Dia_Fallecimiento,Meses_Nombres_Hechos,Dias_Nombres_Hechos,COMUNAS,Area,Densidad_Poblacion,Semestre
0,2016-0001,1,2016-01-01,2016,1,1,1900-01-01 04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,2016-01-01,2016.0,1.0,1.0,Enero,Viernes,8,2.221690e+07,0.010202,1
1,2016-0004,1,2016-01-10,2016,1,10,1900-01-01 00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,NaT,NaN,NaN,NaN,Enero,Domingo,8,2.221690e+07,0.010202,1
2,2016-0008,1,2016-01-24,2016,1,24,1900-01-01 18:30:00,18,AV 27 DE FEBRERO Y AV ESCALADA,AVENIDA,...,2016-01-24,2016.0,1.0,24.0,Enero,Domingo,8,2.221690e+07,0.010202,1
3,2016-0017,1,2016-02-15,2016,2,15,1900-01-01 16:54:00,16,MARIANO ACOSTA Y ANA MARIA JANER,AVENIDA,...,2016-02-16,2016.0,2.0,16.0,Febrero,Lunes,8,2.221690e+07,0.010202,1
4,2016-0025,1,2016-02-28,2016,2,28,1900-01-01 04:50:00,4,AV GRAL PAZ Y AV 27 DE FEBRERO,GRAL PAZ,...,2016-02-28,2016.0,2.0,28.0,Febrero,Domingo,8,2.221690e+07,0.010202,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
710,2020-0019,1,2020-03-10,2020,3,10,1900-01-01 21:00:00,21,CONSTITUCION Y CASTRO,CALLE,...,2020-03-10,2020.0,3.0,10.0,Marzo,Martes,5,6.660603e+06,0.028069,1
711,2021-0004,1,2021-01-11,2021,1,11,1900-01-01 09:12:18,9,CASEROS AV. Y GUARANI,AVENIDA,...,2021-01-11,2021.0,1.0,11.0,Enero,Lunes,5,6.660603e+06,0.028069,1
712,2021-0020,1,2021-02-21,2021,2,21,1900-01-01 15:00:00,15,POTOSI Y GASCON,CALLE,...,2021-02-21,2021.0,2.0,21.0,Febrero,Domingo,5,6.660603e+06,0.028069,1
713,2021-0033,1,2021-04-14,2021,4,14,1900-01-01 17:50:00,17,AU 25 DE MAYO ALTURA BAJADA BOEDO AV.,AUTOPISTA,...,2021-04-14,2021.0,4.0,14.0,Abril,Miércoles,5,6.660603e+06,0.028069,1
714,2021-0060,1,2021-07-22,2021,7,22,1900-01-01 12:30:00,12,"SALGUERO, JERONIMO Y RIVADAVIA AV.",AVENIDA,...,2021-07-22,2021.0,7.0,22.0,Julio,Jueves,5,6.660603e+06,0.028069,2

###  Crear un DataFrame con las Columnas Necesarias

In [9]:
kpi.columns

Index(['Id', 'N°_Victimas', 'Fecha_Hechos', 'Año_Hechos', 'Mes_Hechos',
       'Dia_Hechos', 'Hora_Completa_Hechos', 'Hora_Hechos', 'Lugar_Del_Hecho',
       'Tipo_De_Calle', 'Calle', 'Altura', 'Cruce', 'Dirección Normalizada',
       'Comuna', 'Barrios', 'Poblacion', 'Geo_Localizacion', 'Longitud',
       'Latitud', 'Victima', 'Sexo', 'Edad', 'Rol_Victima', 'Acusado',
       'Participantes', 'Fecha_Fallecimiento', 'Año_Fallecimiento',
       'Mes_Fallecimiento', 'Dia_Fallecimiento', 'Meses_Nombres_Hechos',
       'Dias_Nombres_Hechos', 'COMUNAS', 'Area', 'Densidad_Poblacion',
       'Semestre'],
      dtype='object')

In [10]:
# Se define variable para resolver el primer kpi
kpi_1 = kpi[['Id', 'N°_Victimas', 'Año_Hechos','Semestre', 'Comuna', 'Poblacion']]

In [27]:
# Se calcula el total poblacion de caba
caba_total_habitantes = habitantes_por_comuna['POBLACION'].sum()
caba_total_habitantes

3063728

In [28]:
# Se calcula el numero de homicidios
numero_Victimas = kpi['N°_Victimas'].sum()
numero_Victimas

759

In [29]:
# Se agrupa y agrega la columna
numero_victimas_año_semestre =  (kpi.groupby(['Año_Hechos', 'Semestre'], as_index=False).agg({'N°_Victimas': 'sum'}))

In [30]:
# Visualizar el DataFrame
numero_victimas_año_semestre

    Año_Hechos  Semestre  N°_Victimas
0         2016         1           67
1         2016         2           81
2         2017         1           81
3         2017         2           79
4         2018         1           76
5         2018         2           85
6         2019         1           59
7         2019         2           47
8         2020         1           31
9         2020         2           56
10        2021         1           55
11        2021         2           42

In [33]:
def tasa_hsv_hab(año,semestre):
    
    """"Funcion devuelve la tasa de homicidios cada 100000 habitantes
        en un año y semestres ingresados en los parametros"""
        
    # Filtra el año y el semestre
    filtro_año_semestre = numero_victimas_año_semestre[(numero_victimas_año_semestre['Semestre'] == semestre) & (numero_victimas_año_semestre['Año_Hechos'] == año)]    

    # FIltra el valor de cada columna
    filtro_victimas_año = int(filtro_año_semestre['Año_Hechos'].iloc[0])
    filtro_victimas_semestre = int(filtro_año_semestre['Semestre'].iloc[0])
    filtro_victimas = int(filtro_año_semestre['N°_Victimas'].iloc[0])
    
    # Variable calcula la tasa
    tasa_hom_sv_hab_ingresado = round((filtro_victimas / caba_total_habitantes) * 100000, 2)
    
    return f'La Tasa de homicidios en siniestros viales por cada 100,000 habitantes, para el Semestre {filtro_victimas_semestre} del "Año" {filtro_victimas_año} es de: {tasa_hom_sv_hab_ingresado}'

In [34]:
tasa_hsv_hab(2020,2)

'La Tasa de homicidios en siniestros viales por cada 100,000 habitantes, para el Semestre 2 del "Año" 2020 es de: 1.83'

In [ ]:
def tasa_hsv_hab_ant(año_ant,semestre_ant): 
    
    """"Funcion devuelve la tasa de homicidios cada 100000 habitantes
        en un año y semestres anteriores a los ingresados en los parametros.
        Es similar a la tasa_hsv_hab pero se modifican los parametros"""
    
    # Filtra el año y el semestre
    filtro_año_semestre_ant = numero_hsv_aa_semestre[(numero_hsv_aa_semestre['SEMESTRE'] == semestre_ant) & (numero_hsv_aa_semestre['AAAA'] == año_ant)]    
   
    # FIltra el valor de cada columna
    filtro_victimas_año_ant = int(filtro_año_semestre_ant['AAAA'].iloc[0])
    filtro_victimas_semestre_ant = int(filtro_año_semestre_ant['SEMESTRE'].iloc[0])
    filtro_victimas_ant = int(filtro_año_semestre_ant['N_VICTIMAS'].iloc[0])
    
    # Variable calcula la tasa
    tasa_hom_sv_hab_ingresado_ant = round((filtro_victimas_ant / caba_total_habitantes) * 100000, 2)
    
    return f'La Tasa de homicidios en siniestros viales por cada 100,000 habitantes, para el Semestre {filtro_victimas_semestre_ant} del "Año" {filtro_victimas_año_ant} es de: {tasa_hom_sv_hab_ingresado_ant} '

In [ ]:
tasa_hsv_hab_ant(2016,1)

In [ ]:
def kpi_1(año_kpi, semestre_kpi):
    
    """ Esta funcion devuelve la tasa del año, semestre y victimas del ingresados
        y el semestre anteior al ingresado """
    
    if año_kpi <= 2016 and semestre_kpi == 1:
        return f'No hay Datos Menores al "Año" 2016 "Semestre" 1 para hacer la comparacion entre Semestres'
    elif año_kpi >= 2022 and semestre_kpi == 1:
        return f'No hay Datos Mayores al "Año" 2022 "Semestre" 1 para hacer la comparacion entre Semestres'
    
    
    if (semestre_kpi == 2):
        semestre = semestre_kpi
        semestre_ant = (semestre_kpi - 1)
        año_ant = año_kpi
        año = año_kpi  
        #return tasa_hsv_hab(año, semestre), tasa_hsv_hab_ant(año_ant,semestre_ant) 
    else:
        año_ant = (año_kpi - 1)
        año = año_kpi
        semestre = semestre_kpi
        semestre_ant = (semestre_kpi + 1)
        #return tasa_hsv_hab(año, semestre), tasa_hsv_hab_ant(año_ant,semestre_ant)
        
        
    return tasa_hsv_hab(año, semestre), tasa_hsv_hab_ant(año_ant,semestre_ant)

In [ ]:
kpi_1(2021,2)

***
***
# KPI_2

   2_ Reducir en un 7% la cantidad de accidentes mortales de motociclistas en el último año, en CABA, respecto al año anterior.

- Definimos a la cantidad de accidentes mortales de motociclistas en siniestros viales como el número absoluto de accidentes fatales en los que estuvieron involucradas víctimas que viajaban en moto en un determinado periodo temporal. Su fórmula para medir la evolución de los accidentes mortales con víctimas en moto es: (Número de accidentes mortales con víctimas en moto en el año anterior - Número de accidentes mortales con víctimas en moto en el año actual) / (Número de accidentes mortales con víctimas en moto en el año anterior) * 100

***

### - Carga del DataFrame